/*

 @projectDescription An cross-browser implementation of the HTML5 <canvas> text methods
 @author Fabien Menager
 @version $Revision$
 @license MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
window.Canvas=window.Canvas||{};
window.Canvas.Text={equivalentFaces:{arial:["liberation sans","nimbus sans l","freesans","optimer","dejavu sans"],"times new roman":["liberation serif","helvetiker","linux libertine","freeserif"],"courier new":["dejavu sans mono","liberation mono","nimbus mono l","freemono"],georgia:["nimbus roman no9 l","helvetiker"],helvetica:["nimbus sans l","helvetiker","freesans"],tahoma:["dejavu sans","optimer","bitstream vera sans"],verdana:["dejavu sans","optimer","bitstream vera sans"]},genericFaces:{serif:["times new roman",
"georgia","garamond","bodoni","minion web","itc stone serif","bitstream cyberbit"],"sans-serif":["arial","verdana","trebuchet","tahoma","helvetica","itc avant garde gothic","univers","futura","gill sans","akzidenz grotesk","attika","typiko new era","itc stone sans","monotype gill sans 571"],monospace:["courier","courier new","prestige","everson mono"],cursive:["caflisch script","adobe poetica","sanvito","ex ponto","snell roundhand","zapf-chancery"],fantasy:["alpha geometrique","critter","cottonwood",
"fb reactor","studz"]},faces:{},scaling:0.962,_styleCache:{}};
(function(){function p(a){switch(String(a)){case "bolder":case "bold":case "900":case "800":case "700":return"bold";case "600":case "500":case "400":default:case "normal":return"normal"}}function n(a){if(document.defaultView&&document.defaultView.getComputedStyle)return document.defaultView.getComputedStyle(a,null);return a.currentStyle||a.style}var q=window.opera&&/Opera\/9/.test(navigator.userAgent),j=window.CanvasRenderingContext2D?window.CanvasRenderingContext2D.prototype:document.createElement("canvas").getContext("2d").__proto__,
h=window.Canvas.Text;h.options={fallbackCharacter:" ",dontUseMoz:false,reimplement:false,debug:false,autoload:false};h.triedLoading=[];var m=document.getElementsByTagName("script"),k;for(var l in m)if(m[l].src&&m[l].src.indexOf("canvas.text")!=-1){k=m[l].src.split("?");break}h.basePath=k[0].substr(0,k[0].lastIndexOf("/")+1);if(k[1]){m=k[1].split("&");for(k=m.length-1;k>=0;--k){var r=m[k].split("=");h.options[r[0]]=r[1]}}var o=!h.options.dontUseMoz&&j.mozDrawText&&!j.fillText;if(j.fillText&&!h.options.reimplement&&
!/iphone/i.test(navigator.userAgent))return window._typeface_js={loadFace:function(){}};h.lookupFamily=function(a){var c=this.faces,b,d,f=this.equivalentFaces,e=this.genericFaces;if(c[a])return c[a];if(e[a])for(b=0;b<e[a].length;b++)if(d=this.lookupFamily(e[a][b]))return d;if(!(d=f[a]))return false;for(b=0;b<d.length;b++)if(a=c[d[b]])return a;return false};h.getFace=function(a,c,b){var d=a.replace(/[ -]/g,"_")+"-"+c+"-"+b,f=this.triedLoading[d],e=this.lookupFamily(a);if(!e&&f)return false;if(e&&e[c]&&
e[c][b])return e[c][b];if(!this.options.autoload||f)return false;f=this.basePath+this.options.autoload+"/"+d+".js";var g;try{g=new ActiveXObject("Msxml2.XMLHTTP")}catch(i){try{g=new ActiveXObject("Microsoft.XMLHTTP")}catch(s){try{g=new XMLHttpRequest}catch(t){g=false}}}g=g;try{this.triedLoading[d]=1;g.open("get",f,false);g.send(null);if(g.status==200||g.status==0)try{eval(g.responseText);window.status=" ";return this.faces[a][c][b]}catch(u){window.status="Error installing the font ["+a+" "+c+" "+
b+"]"}else window.status="Unable to load the font ["+a+" "+c+" "+b+"]"}catch(v){window.status="Error loading the font ["+a+" "+c+" "+b+"]"}};h.loadFace=function(a){var c=a.familyName.toLowerCase();this.faces[c]=this.faces[c]||{};if(a.strokeFont){this.faces[c].normal=this.faces[c].normal||{};this.faces[c].normal.normal=a;this.faces[c].normal.italic=a;this.faces[c].bold=this.faces[c].normal||{};this.faces[c].bold.normal=a;this.faces[c].bold.italic=a}else{this.faces[c][a.cssFontWeight]=this.faces[c][a.cssFontWeight]||
{};this.faces[c][a.cssFontWeight][a.cssFontStyle]=a}return a};window._typeface_js={faces:h.faces,loadFace:h.loadFace};h.getFaceFromStyle=function(a){var c=p(a.weight),b=a.family,d,f;for(d=0;d<b.length;d++)if(f=this.getFace(b[d].toLowerCase().replace(/^-webkit-/,""),c,a.style))return f;return false};try{j.font="10px sans-serif";j.textAlign="start";j.textBaseline="alphabetic"}catch(w){}j.parseStyle=function(a){if(h._styleCache[a])return this.getComputedStyle(h._styleCache[a]);var c={},b;if(!this._elt){this._elt=
document.createElement("span");this.canvas.appendChild(this._elt)}this.canvas.font="10px sans-serif";this._elt.style.font=a;b=n(this._elt);c.size=b.fontSize;c.weight=p(b.fontWeight);c.style=b.fontStyle;b=b.fontFamily.split(",");for(l=0;l<b.length;l++)b[l]=b[l].replace(/^["'\s]*/,"").replace(/["'\s]*$/,"");c.family=b;return this.getComputedStyle(h._styleCache[a]=c)};j.buildStyle=function(a){return a.style+" "+a.weight+" "+a.size+'px "'+a.family+'"'};j.renderText=function(a,c){var b=h.getFaceFromStyle(c),
d=c.size/b.resolution*0.75,f=0,e,g=String(a).split(""),i=g.length;if(!q){this.scale(d,-d);this.lineWidth/=d}for(e=0;e<i;e++)f+=this.renderGlyph(g[e],b,d,f)};j.renderGlyph=q?function(a,c,b,d){var f,e,g,i=c.glyphs[a]||c.glyphs[h.options.fallbackCharacter];if(i){if(i.o){c=i._cachedOutline||(i._cachedOutline=i.o.split(" "));g=c.length;for(a=0;a<g;){f=c[a++];switch(f){case "m":this.moveTo(c[a++]*b+d,c[a++]*-b);break;case "l":this.lineTo(c[a++]*b+d,c[a++]*-b);break;case "q":f=c[a++]*b+d;e=c[a++]*-b;this.quadraticCurveTo(c[a++]*
b+d,c[a++]*-b,f,e);break;case "b":f=c[a++]*b+d;e=c[a++]*-b;this.bezierCurveTo(c[a++]*b+d,c[a++]*-b,c[a++]*b+d,c[a++]*-b,f,e);break}}}return i.ha*b}}:function(a,c){var b,d,f,e,g,i=c.glyphs[a]||c.glyphs[h.options.fallbackCharacter];if(i){if(i.o){e=i._cachedOutline||(i._cachedOutline=i.o.split(" "));g=e.length;for(b=0;b<g;){d=e[b++];switch(d){case "m":this.moveTo(e[b++],e[b++]);break;case "l":this.lineTo(e[b++],e[b++]);break;case "q":d=e[b++];f=e[b++];this.quadraticCurveTo(e[b++],e[b++],d,f);break;case "b":d=
e[b++];f=e[b++];this.bezierCurveTo(e[b++],e[b++],e[b++],e[b++],d,f);break}}}i.ha&&this.translate(i.ha,0)}};j.getTextExtents=function(a,c){var b=0,d=0,f=h.getFaceFromStyle(c),e,g=a.length,i;for(e=0;e<g;e++){i=f.glyphs[a.charAt(e)]||f.glyphs[h.options.fallbackCharacter];b+=Math.max(i.ha,i.x_max);d+=i.ha}return{width:b,height:f.lineHeight,ha:d}};j.getComputedStyle=function(a){var c,b=n(this.canvas),d={},f=a.size;b=parseFloat(b.fontSize);var e=parseFloat(f);for(c in a)d[c]=a[c];d.size=typeof f==="number"||
f.indexOf("px")!=-1?e:f.indexOf("em")!=-1?b*e:f.indexOf("%")!=-1?b/100*e:f.indexOf("pt")!=-1?e/0.75:b;return d};j.getTextOffset=function(a,c,b){var d=n(this.canvas);a=this.measureText(a);c=c.size/b.resolution*0.75;var f={x:0,y:0,metrics:a,scale:c};switch(this.textAlign){default:case null:case "left":break;case "center":f.x=-a.width/2;break;case "right":f.x=-a.width;break;case "start":f.x=d.direction=="rtl"?-a.width:0;break;case "end":f.x=d.direction=="ltr"?-a.width:0;break}switch(this.textBaseline){case "alphabetic":break;
default:case null:case "ideographic":case "bottom":f.y=b.descender;break;case "hanging":case "top":f.y=b.ascender;break;case "middle":f.y=(b.ascender+b.descender)/2;break}f.y*=c;return f};j.drawText=function(a,c,b,d,f){d=this.parseStyle(this.font);var e=h.getFaceFromStyle(d),g=this.getTextOffset(a,d,e);this.save();this.translate(c+g.x,b+g.y);if(e.strokeFont&&!f)this.strokeStyle=this.fillStyle;this.lineCap="round";this.beginPath();if(o){this.mozTextStyle=this.buildStyle(d);this[f?"mozPathText":"mozDrawText"](a)}else{this.scale(h.scaling,
h.scaling);this.renderText(a,d);if(e.strokeFont)this.lineWidth=2+d.size*(d.weight=="bold"?0.08:0.015)/2}this[f||e.strokeFont&&!o?"stroke":"fill"]();this.closePath();this.restore();if(h.options.debug){a=Math.floor(g.x+c)+0.5;b=Math.floor(b)+0.5;this.save();this.strokeStyle="#F00";this.lineWidth=0.5;this.beginPath();this.moveTo(a+g.metrics.width,b);this.lineTo(a,b);this.moveTo(a-g.x,b+g.y);this.lineTo(a-g.x,b+g.y-d.size);this.stroke();this.closePath();this.restore()}};j.fillText=function(a,c,b,d){this.drawText(a,
c,b,d,false)};j.strokeText=function(a,c,b,d){this.drawText(a,c,b,d,true)};j.measureText=function(a){var c=this.parseStyle(this.font),b={width:0};if(o){this.mozTextStyle=this.buildStyle(c);b.width=this.mozMeasureText(a)}else{var d=h.getFaceFromStyle(c);d=c.size/d.resolution*0.75;b.width=this.getTextExtents(a,c).ha*d*h.scaling}return b}})();
