/*

 // Copyright 2006 Google Inc.
 //
 // Licensed under the Apache License, Version 2.0 (the "License");
 // you may not use this file except in compliance with the License.
 // You may obtain a copy of the License at
 //
 //   http://www.apache.org/licenses/LICENSE-2.0
 //
 // Unless required by applicable law or agreed to in writing, software
 // distributed under the License is distributed on an "AS IS" BASIS,
 // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 // See the License for the specific language governing permissions and
 // limitations under the License.
*/
document.createElement("canvas").getContext||function(){function M(){return this.context_||(this.context_=new x(this))}function N(a,b){var c=G.call(arguments,2);return function(){return a.apply(b,c.concat(G.call(arguments)))}}function H(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!a.styleSheets.ex_canvas_)a=a.createStyleSheet(),a.owningElement.id=
"ex_canvas_",a.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}"}function O(a){var b=a.srcElement;switch(a.propertyName){case "width":b.getContext().clearRect();b.style.width=b.attributes.width.nodeValue+"px";b.firstChild.style.width=b.clientWidth+"px";break;case "height":b.getContext().clearRect(),b.style.height=b.attributes.height.nodeValue+"px",b.firstChild.style.height=b.clientHeight+"px"}}function P(a){a=a.srcElement;if(a.firstChild)a.firstChild.style.width=
a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px"}function y(){return[[1,0,0],[0,1,0],[0,0,1]]}function o(a,b){for(var c=y(),g=0;g<3;g++)for(var e=0;e<3;e++){for(var f=0,d=0;d<3;d++)f+=a[g][d]*b[d][e];c[g][e]=f}return c}function I(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;
b.globalAlpha=a.globalAlpha;b.font=a.font;b.textAlign=a.textAlign;b.textBaseline=a.textBaseline;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function J(a){var b=a.indexOf("(",3),c=a.indexOf(")",b+1),b=a.substring(b+1,c).split(",");if(b.length!=4||a.charAt(3)!="a")b[3]=1;return b}function z(a,b,c){return Math.min(c,Math.max(b,a))}function A(a,b,c){c<0&&c++;c>1&&c--;return 6*c<1?a+(b-a)*6*c:2*c<1?b:3*c<2?a+(b-a)*(2/3-c)*6:a}function B(a){if(a in C)return C[a];var b,
c=1,a=String(a);if(a.charAt(0)=="#")b=a;else if(/^rgb/.test(a)){c=J(a);b="#";for(var g,e=0;e<3;e++)g=c[e].indexOf("%")!=-1?Math.floor(parseFloat(c[e])/100*255):+c[e],b+=r[z(g,0,255)];c=+c[3]}else if(/^hsl/.test(a)){e=c=J(a);b=parseFloat(e[0])/360%360;b<0&&b++;g=z(parseFloat(e[1])/100,0,1);e=z(parseFloat(e[2])/100,0,1);if(g==0)g=e=b=e;else{var f=e<0.5?e*(1+g):e+g-e*g,d=2*e-f;g=A(d,f,b+1/3);e=A(d,f,b);b=A(d,f,b-1/3)}b="#"+r[Math.floor(g*255)]+r[Math.floor(e*255)]+r[Math.floor(b*255)];c=c[3]}else b=
Q[a]||a;return C[a]={color:b,alpha:c}}function x(a){this.m_=y();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=i*1;this.globalAlpha=1;this.font="10px sans-serif";this.textAlign="left";this.textBaseline="alphabetic";this.canvas=a;var b="width:"+a.clientWidth+"px;height:"+a.clientHeight+"px;position:absolute",c=a.ownerDocument.createElement("div");c.style.cssText=b;a.appendChild(c);
b=c.cloneNode(!1);b.style.backgroundColor="red";b.style.filter="alpha(opacity=0)";a.appendChild(b);this.element_=c;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function K(a,b,c,g){a.currentPath_.push({type:"bezierCurveTo",cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:g.x,y:g.y});a.currentX_=g.x;a.currentY_=g.y}function R(a,b,c,g){var e=a.fillStyle,f=a.arcScaleX_,d=a.arcScaleY_,h=g.x-c.x,n=g.y-c.y;if(e instanceof s){var j=0,g={x:0,y:0},q=0,l=1;if(e.type_=="gradient"){var j=e.x1_/f,c=e.y1_/d,p=k(a,e.x0_/
f,e.y0_/d),j=k(a,j,c),j=Math.atan2(j.x-p.x,j.y-p.y)*180/Math.PI;j<0&&(j+=360);j<1.0E-6&&(j=0)}else p=k(a,e.x0_,e.y0_),g={x:(p.x-c.x)/h,y:(p.y-c.y)/n},h/=f*i,n/=d*i,l=t.max(h,n),q=2*e.r0_/l,l=2*e.r1_/l-q;f=e.colors_;f.sort(function(a,b){return a.offset-b.offset});for(var d=f.length,p=f[0].color,c=f[d-1].color,h=f[0].alpha*a.globalAlpha,a=f[d-1].alpha*a.globalAlpha,n=[],m=0;m<d;m++){var o=f[m];n.push(o.offset*l+q+" "+o.color)}b.push('<g_vml_:fill type="',e.type_,'"',' method="none" focus="100%"',' color="',
p,'"',' color2="',c,'"',' colors="',n.join(","),'"',' opacity="',a,'"',' g_o_:opacity2="',h,'"',' angle="',j,'"',' focusposition="',g.x,",",g.y,'" />')}else e instanceof D?h&&n&&b.push("<g_vml_:fill",' position="',-c.x/h*f*f,",",-c.y/n*d*d,'"',' type="tile"',' src="',e.src_,'" />'):(e=B(a.fillStyle),b.push('<g_vml_:fill color="',e.color,'" opacity="',e.alpha*a.globalAlpha,'" />'))}function k(a,b,c){a=a.m_;return{x:i*(b*a[0][0]+c*a[1][0]+a[2][0])-m,y:i*(b*a[0][1]+c*a[1][1]+a[2][1])-m}}function u(a,
b,c){if(isFinite(b[0][0])&&isFinite(b[0][1])&&isFinite(b[1][0])&&isFinite(b[1][1])&&isFinite(b[2][0])&&isFinite(b[2][1])&&(a.m_=b,c))a.lineScale_=S(T(b[0][0]*b[1][1]-b[0][1]*b[1][0]))}function s(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function D(a,b){if(!a||a.nodeType!=1||a.tagName!="IMG")throw new v("TYPE_MISMATCH_ERR");if(a.readyState!="complete")throw new v("INVALID_STATE_ERR");switch(b){case "repeat":case null:case "":this.repetition_="repeat";break;
case "repeat-x":case "repeat-y":case "no-repeat":this.repetition_=b;break;default:throw new v("SYNTAX_ERR");}this.src_=a.src;this.width_=a.width;this.height_=a.height}function v(a){this.code=this[a];this.message=a+": DOM Exception "+this.code}var t=Math,h=t.round,E=t.sin,F=t.cos,T=t.abs,S=t.sqrt,i=10,m=i/2;navigator.userAgent.match(/MSIE ([\d.]+)?/);var G=Array.prototype.slice;H(document);var L={init:function(a){a=a||document;a.createElement("canvas");a.attachEvent("onreadystatechange",N(this.init_,
this,a))},init_:function(a){for(var a=a.getElementsByTagName("canvas"),b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=M;H(a.ownerDocument);a.innerHTML="";a.attachEvent("onpropertychange",O);a.attachEvent("onresize",P);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};L.init();for(var r=[],d=
0;d<16;d++)for(var w=0;w<16;w++)r[d*16+w]=d.toString(16)+w.toString(16);var Q={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",bisque:"#FFE4C4",black:"#000000",blanchedalmond:"#FFEBCD",blueviolet:"#8A2BE2",brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",
darkgray:"#A9A9A9",darkgreen:"#006400",darkgrey:"#A9A9A9",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",darksalmon:"#E9967A",darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",darkslategray:"#2F4F4F",darkslategrey:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",deepskyblue:"#00BFFF",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",
gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",goldenrod:"#DAA520",grey:"#808080",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",ivory:"#FFFFF0",khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgreen:"#90EE90",lightgrey:"#D3D3D3",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",
lightskyblue:"#87CEFA",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",mediumaquamarine:"#66CDAA",mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370DB",mediumseagreen:"#3CB371",mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",
oldlace:"#FDF5E6",olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#DB7093",papayawhip:"#FFEFD5",peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",powderblue:"#B0E0E6",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",skyblue:"#87CEEB",slateblue:"#6A5ACD",slategray:"#708090",
slategrey:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",whitesmoke:"#F5F5F5",yellowgreen:"#9ACD32"},C={},U={butt:"flat",round:"round"},d=x.prototype;d.clearRect=function(){if(this.textMeasureEl_)this.textMeasureEl_.removeNode(!0),this.textMeasureEl_=null;this.element_.innerHTML=""};d.beginPath=function(){this.currentPath_=[]};d.moveTo=function(a,b){var c=k(this,a,b);this.currentPath_.push({type:"moveTo",
x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.lineTo=function(a,b){var c=k(this,a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.bezierCurveTo=function(a,b,c,g,e,f){e=k(this,e,f);a=k(this,a,b);c=k(this,c,g);K(this,a,c,e)};d.quadraticCurveTo=function(a,b,c,g){a=k(this,a,b);c=k(this,c,g);g={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};K(this,g,{x:g.x+(c.x-this.currentX_)/3,y:g.y+(c.y-this.currentY_)/3},
c)};d.arc=function(a,b,c,g,e,f){c*=i;var d=f?"at":"wa",h=a+F(g)*c-m,n=b+E(g)*c-m,g=a+F(e)*c-m,e=b+E(e)*c-m;h==g&&!f&&(h+=0.125);a=k(this,a,b);h=k(this,h,n);g=k(this,g,e);this.currentPath_.push({type:d,x:a.x,y:a.y,radius:c,xStart:h.x,yStart:h.y,xEnd:g.x,yEnd:g.y})};d.rect=function(a,b,c,g){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+g);this.lineTo(a,b+g);this.closePath()};d.strokeRect=function(a,b,c,g){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+
c,b+g);this.lineTo(a,b+g);this.closePath();this.stroke();this.currentPath_=e};d.fillRect=function(a,b,c,g){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+g);this.lineTo(a,b+g);this.closePath();this.fill();this.currentPath_=e};d.createLinearGradient=function(a,b,c,g){var e=new s("gradient");e.x0_=a;e.y0_=b;e.x1_=c;e.y1_=g;return e};d.createRadialGradient=function(a,b,c,g,e,f){var d=new s("gradientradial");d.x0_=a;d.y0_=b;d.r0_=c;d.x1_=g;d.y1_=e;d.r1_=
f;return d};d.drawImage=function(a){var b,c,g,e,d,m,o,n;g=a.runtimeStyle.width;e=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var j=a.width,q=a.height;a.runtimeStyle.width=g;a.runtimeStyle.height=e;if(arguments.length==3)b=arguments[1],c=arguments[2],d=m=0,o=g=j,n=e=q;else if(arguments.length==5)b=arguments[1],c=arguments[2],g=arguments[3],e=arguments[4],d=m=0,o=j,n=q;else if(arguments.length==9)d=arguments[1],m=arguments[2],o=arguments[3],n=arguments[4],b=arguments[5],
c=arguments[6],g=arguments[7],e=arguments[8];else throw Error("Invalid number of arguments");var l=k(this,b,c),p=[];p.push(" <g_vml_:group",' coordsize="',i*10,",",i*10,'"',' coordorigin="0,0"',' style="width:',10,"px;height:",10,"px;position:absolute;");if(this.m_[0][0]!=1||this.m_[0][1]||this.m_[1][1]!=1||this.m_[1][0]){var r=[];r.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",h(l.x/i),",","Dy=",h(l.y/i),"");var s=k(this,b+g,c),u=k(this,
b,c+e);b=k(this,b+g,c+e);l.x=t.max(l.x,s.x,u.x,b.x);l.y=t.max(l.y,s.y,u.y,b.y);p.push("padding:0 ",h(l.x/i),"px ",h(l.y/i),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",r.join(""),", sizingmethod='clip');")}else p.push("top:",h(l.y/i),"px;left:",h(l.x/i),"px;");p.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',i*g,"px;"," height:",i*e,'px"',' cropleft="',d/j,'"',' croptop="',m/q,'"',' cropright="',(j-d-o)/j,'"',' cropbottom="',(q-m-n)/q,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",
p.join(""))};d.stroke=function(a){var b=[];b.push("<g_vml_:shape",' filled="',!!a,'"',' style="position:absolute;width:',10,"px;height:",10,'px;"',' coordorigin="0,0"',' coordsize="',i*10,",",i*10,'"',' stroked="',!a,'"',' path="');for(var c={x:null,y:null},d={x:null,y:null},e=0;e<this.currentPath_.length;e++){var f=this.currentPath_[e];switch(f.type){case "moveTo":b.push(" m ",h(f.x),",",h(f.y));break;case "lineTo":b.push(" l ",h(f.x),",",h(f.y));break;case "close":b.push(" x ");f=null;break;case "bezierCurveTo":b.push(" c ",
h(f.cp1x),",",h(f.cp1y),",",h(f.cp2x),",",h(f.cp2y),",",h(f.x),",",h(f.y));break;case "at":case "wa":b.push(" ",f.type," ",h(f.x-this.arcScaleX_*f.radius),",",h(f.y-this.arcScaleY_*f.radius)," ",h(f.x+this.arcScaleX_*f.radius),",",h(f.y+this.arcScaleY_*f.radius)," ",h(f.xStart),",",h(f.yStart)," ",h(f.xEnd),",",h(f.yEnd))}if(f){if(c.x==null||f.x<c.x)c.x=f.x;if(d.x==null||f.x>d.x)d.x=f.x;if(c.y==null||f.y<c.y)c.y=f.y;if(d.y==null||f.y>d.y)d.y=f.y}}b.push(' ">');a?R(this,b,c,d):(c=B(this.strokeStyle),
a=c.color,c=c.alpha*this.globalAlpha,d=this.lineScale_*this.lineWidth,d<1&&(c*=d),b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',this.miterLimit,'"',' endcap="',U[this.lineCap]||"square",'"',' weight="',d,'px"',' color="',a,'" />'));b.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",b.join(""))};d.fill=function(){this.stroke(!0)};d.closePath=function(){this.currentPath_.push({type:"close"})};d.save=function(){var a={};I(this,a);this.aStack_.push(a);
this.mStack_.push(this.m_);this.m_=o(y(),this.m_)};d.restore=function(){if(this.aStack_.length)I(this.aStack_.pop(),this),this.m_=this.mStack_.pop()};d.translate=function(a,b){u(this,o([[1,0,0],[0,1,0],[a,b,1]],this.m_),!1)};d.rotate=function(a){var b=F(a),a=E(a);u(this,o([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};d.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;u(this,o([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};d.transform=function(a,b,c,d,e,f){u(this,o([[a,b,0],[c,d,0],[e,f,1]],this.m_),
!0)};d.setTransform=function(a,b,c,d,e,f){u(this,[[a,b,0],[c,d,0],[e,f,1]],!0)};d.clip=function(){};d.arcTo=function(){};d.createPattern=function(a,b){return new D(a,b)};s.prototype.addColorStop=function(a,b){b=B(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};d=v.prototype=Error();d.INDEX_SIZE_ERR=1;d.DOMSTRING_SIZE_ERR=2;d.HIERARCHY_REQUEST_ERR=3;d.WRONG_DOCUMENT_ERR=4;d.INVALID_CHARACTER_ERR=5;d.NO_DATA_ALLOWED_ERR=6;d.NO_MODIFICATION_ALLOWED_ERR=7;d.NOT_FOUND_ERR=8;d.NOT_SUPPORTED_ERR=
9;d.INUSE_ATTRIBUTE_ERR=10;d.INVALID_STATE_ERR=11;d.SYNTAX_ERR=12;d.INVALID_MODIFICATION_ERR=13;d.NAMESPACE_ERR=14;d.INVALID_ACCESS_ERR=15;d.VALIDATION_ERR=16;d.TYPE_MISMATCH_ERR=17;G_vmlCanvasManager=L;CanvasRenderingContext2D=x;CanvasGradient=s;CanvasPattern=D;DOMException=v}();
