/*

 DHTML Suite for Applications.
 Copyright (C)2006  Alf Magne Kalleland(post@dhtmlgoodies.com)

 www.dhtmlgoodies.com
 Alf Magne Kalleland
*/
if(!window.DHTMLSuite)var DHTMLSuite={};
DHTMLSuite.menuBar=function(){this.cssPrefix="DHTMLSuite_";this.menuItemLayoutCss=!1;this.layoutCSS="menu-bar.css";this.menuBarBackgroundImage="menu_strip_bg.jpg";this.menuItem_objects={};DHTMLSuite.variableStorage.menuBar_highlightedItems=[];this.menuBarObj=this.menuBarState=!1;this.menuBarHeight=26;this.submenuGroups=[];this.submenuIframes=[];this.menuItemCssPrefix=this.activeSubItemsOnMouseOver=this.targetId=!1;this.createIframesForOldIeBrowsers=!0;try{standardObjectsCreated||DHTMLSuite.createStandardObjects()}catch(a){alert("You need to include the dhtmlSuite-common.js file")}this.objectIndex=
DHTMLSuite.variableStorage.arrayDSObjects.length;DHTMLSuite.variableStorage.arrayDSObjects[this.objectIndex]=this};
DHTMLSuite.menuBar.prototype={init:function(){DHTMLSuite.commonObj.loadCSS(this.layoutCSS);this.__createMainMenuDiv();this.__createMenuItems();this.__setBasicEvents();window.refToThismenuBar=this},setTarget:function(a){this.targetId=a},setLayoutCss:function(a){this.layoutCSS=a},setMenuItemLayoutCss:function(a){this.menuItemLayoutCss=a},setCreateIframesForOldIeBrowsers:function(a){this.createIframesForOldIeBrowsers=a},addMenuItems:function(a){this.menuItemObj=a;this.menuItems=a.getItems()},setActiveSubItemsOnMouseOver:function(a){this.activeSubItemsOnMouseOver=
a},setMenuItemState:function(a,b){try{this.menuItem_objects[a].setState(b)}catch(c){alert("menu item with id "+a+" does not exists or you have called the setMenuItemState method before the menu has been initialized")}},setMenuItemCssPrefix:function(a){this.menuItemCssPrefix=a},setCssPrefix:function(a){this.cssPrefix=a},deleteAllMenuItems:function(){this.hideSubMenus();this.__deleteMenuItems(0,!1);this.__clearAllMenuItems()},replaceMenuItems:function(a,b){this.hideSubMenus();this.__deleteMenuItems(a);
this.menuItemObj.__appendMenuModel(b,a);this.__clearAllMenuItems();this.__createMenuItems()},deleteMenuItems:function(a,b){this.__deleteMenuItems(a,b);this.__clearAllMenuItems();this.__createMenuItems()},appendMenuItems:function(a,b){this.hideSubMenus();this.menuItemObj.__appendMenuModel(b,a);this.__clearAllMenuItems();this.__createMenuItems()},hideMenuItem:function(a){this.menuItem_objects[a].hide()},showMenuItem:function(a){this.menuItem_objects[a].show()},setText:function(a,b){this.menuItem_objects[a].setText(b)},
setIcon:function(a,b){this.menuItem_objects[a].setIcon(b)},__clearAllMenuItems:function(){for(var a=0;a<this.menuItemObj.menuItemsOrder.length;a++){var b=this.menuItemObj.menuItemsOrder[a];if(b){if(this.submenuGroups[b]){var c=document.getElementById(this.submenuGroups[b]);DHTMLSuite.discardElement(c);this.submenuGroups[b]=null}this.submenuIframes[b]&&(c=document.getElementById(this.submenuIframes[b]),DHTMLSuite.discardElement(c),this.submenuIframes[b]=null)}}this.submenuGroups=[];this.submenuIframes=
[];this.menuBarObj.innerHTML=""},__deleteMenuItems:function(a,b){b&&this.menuItemObj.__deleteANode(a);if(this.submenuGroups[a]){this.menuItem_objects[a].__setHasSub(!1);this.menuItemObj.__deleteChildNodes(a);var c=document.getElementById(this.submenuGroups[a]);DHTMLSuite.discardElement(c);this.submenuIframes[a]&&DHTMLSuite.discardElement(this.submenuIframes[a]);this.submenuGroups.splice(a,1);this.submenuIframes.splice(a,1)}},__changeMenuBarState:function(){var a=this.getAttribute("objectRef"),b=DHTMLSuite.variableStorage.arrayDSObjects[a],
c=this.id.replace(/[^0-9]/gi,"");if(b.menuItem_objects[c].getState()!="disabled")b.menuBarState=!b.menuBarState,b.menuBarState?(b.hideSubMenus(),setTimeout("DHTMLSuite.variableStorage.arrayDSObjects["+a+"].__expandGroup("+c+")",10)):b.hideSubMenus()},__createMainMenuDiv:function(){window.refTomenuBar=this;this.menuBarObj=document.createElement("DIV");this.menuBarObj.className=this.cssPrefix+"menuBar_"+this.menuItemObj.submenuType[1];document.getElementById(this.targetId)?document.getElementById(this.targetId).appendChild(this.menuBarObj):
alert("No target defined for the menu object")},hideSubMenus:function(a){if(this&&this.tagName){document.all&&(a=event);a=DHTMLSuite.commonObj.getSrcElement(a);if(a.tagName.toLowerCase()=="img")a=a.parentNode;if(!a)return;if(a.className&&a.className.indexOf("arrow")>=0)return}for(a=0;a<DHTMLSuite.variableStorage.menuBar_highlightedItems.length;a++)DHTMLSuite.variableStorage.menuBar_highlightedItems[a].getState()!="disabled"&&DHTMLSuite.variableStorage.menuBar_highlightedItems[a].setState("regular"),
DHTMLSuite.variableStorage.menuBar_highlightedItems[a].__hideGroup();DHTMLSuite.variableStorage.menuBar_highlightedItems=[]},__hideSubMenusAfterSmallDelay:function(){setTimeout("DHTMLSuite.variableStorage.arrayDSObjects["+this.objectIndex+"].hideSubMenus()",15)},__expandGroup:function(a){var b=document.getElementById(this.submenuGroups[a]),c=b.getElementsByTagName("DIV")[0],c=c.id.replace(/[^0-9]/g,"");b.style.visibility="visible";if(this.submenuIframes[a])document.getElementById(this.submenuIframes[a]).style.visibility=
"visible";DHTMLSuite.variableStorage.menuBar_highlightedItems[DHTMLSuite.variableStorage.menuBar_highlightedItems.length]=this.menuItem_objects[c];this.__positionSubMenu(a);if(DHTMLSuite.clientInfoObj.isOpera)c=b.getElementsByTagName("DIV")[0],c.className=c.className.replace("_over","_over")},__activateMenuElements:function(a,b,c){if(!c){document.all&&(a=event);c=DHTMLSuite.commonObj.getSrcElement(a);if(!c.getAttribute("DHTMLSuite_menuItem"))c=c.parentNode;if(!c.getAttribute("DHTMLSuite_menuItem"))c=
c.parentNode}a=c.id.replace(/[^0-9]/g,"");if(this.menuItem_objects[a].getState()!="disabled"&&(this.menuItem_objects[a].setState("over"),this.menuBarState||this.activeSubItemsOnMouseOver))b&&DHTMLSuite.variableStorage.menuBar_highlightedItems.length>0&&this.hideSubMenus(),c="over",b||(c="active"),this.menuItem_objects[a].setState(c),this.submenuGroups[a]&&this.__expandGroup(a),DHTMLSuite.variableStorage.menuBar_highlightedItems[DHTMLSuite.variableStorage.menuBar_highlightedItems.length]=this.menuItem_objects[a],
this.menuItems[a].parentId&&this.__activateMenuElements(!1,!1,document.getElementById(this.menuItem_objects[this.menuItems[a].parentId].divElement))},__createMenuItems:function(){var a=this.objectIndex,b=!1,c=document.getElementsByTagName("DIV");c.length>0&&(b=c[0]);for(c=0;c<this.menuItemObj.menuItemsOrder.length;c++){var d=this.menuItemObj.menuItemsOrder[c];if(this.menuItems[d].id){try{this.menuItem_objects[this.menuItems[d].id]=new DHTMLSuite.menuItem}catch(h){alert("Error: You need to include dhtmlSuite-menuItem.js in your html file")}this.menuItemCssPrefix&&
this.menuItem_objects[this.menuItems[d].id].setCssPrefix(this.menuItemCssPrefix);this.menuItemLayoutCss&&this.menuItem_objects[this.menuItems[d].id].setLayoutCss(this.menuItemLayoutCss);var f=this.menuItem_objects[this.menuItems[d].id].createItem(this.menuItems[d]);f.setAttribute("DHTMLSuite_menuItem",1);if(!this.menuItems[d].separator)f.onmouseover=function(b){DHTMLSuite.variableStorage.arrayDSObjects[a].__activateMenuElements(b,!0)};if(!this.menuItems[d].jsFunction&&!this.menuItems[d].url)f.setAttribute("objectRef",
a),f.onclick=this.__changeMenuBarState;DHTMLSuite.commonObj.__addEventEl(f);var e=this.menuBarObj;if(this.menuItems[d].depth==1&&this.menuItemObj.submenuType[this.menuItems[d].depth]!="top"&&this.menuItemObj.mainMenuGroupWidth){var g=this.menuItemObj.mainMenuGroupWidth+"";g.indexOf("%")==-1&&(g+="px");e.style.width=g}if(this.menuItems[d].depth=="1"){if(this.menuItemObj.submenuType[this.menuItems[d].depth]=="top")f.style.styleFloat="left",f.style.cssText="float:left"}else{if(!this.menuItems[d].depth){alert("Error in menu model(depth not defined for a menu item). Remember to call the init()method for the menuModel object.");
return}if(!this.submenuGroups[this.menuItems[d].parentId]){this.submenuGroups[this.menuItems[d].parentId]="DHTMLSuite_menuBarSubGroup"+this.menuItems[d].parentId;e=document.createElement("DIV");e.style.zIndex=1E4+this.menuItems[d].depth;e.style.position="absolute";if(this.menuItems[this.menuItems[d].parentId].groupHeight)g=this.menuItems[this.menuItems[d].parentId].groupHeight,e.style.height=g+"px",e.height=g,e.style.overflow="auto";e.id=this.submenuGroups[this.menuItems[d].parentId];e.style.visibility=
"hidden";e.className=this.cssPrefix+"menuBar_"+this.menuItemObj.submenuType[this.menuItems[d].depth];b?b.parentNode.insertBefore(e,b):document.body.appendChild(e);if(DHTMLSuite.clientInfoObj.isOldMSIE&&this.createIframesForOldIeBrowsers)this.submenuIframes[this.menuItems[d].parentId]="DHTMLSuite_menuBarIframe_"+this.menuItems[d].parentId,e=document.createElement('<IFRAME src="about:blank" frameborder=0>'),e.id=this.submenuIframes[this.menuItems[d].parentId],e.style.position="absolute",e.style.zIndex=
9E3,e.style.visibility="hidden",b?b.parentNode.insertBefore(e,b):document.body.appendChild(e)}e=document.getElementById(this.submenuGroups[this.menuItems[d].parentId])}e.appendChild(f);this.menuItems[d].visible==!1&&this.hideMenuItem(this.menuItems[d].id);this.menuItems[d].state!="regular"&&this.menuItem_objects[this.menuItems[d].id].setState(this.menuItems[d].state)}}this.__setSizeOfAllSubMenus();this.__positionAllSubMenus();DHTMLSuite.clientInfoObj.isOpera&&this.__fixMenuLayoutForOperaBrowser()},
__fixMenuLayoutForOperaBrowser:function(){for(var a=0;a<this.menuItemObj.menuItemsOrder.length;a++){var b=this.menuItemObj.menuItemsOrder[a];if(b)document.getElementById(this.menuItem_objects[b].divElement).className=document.getElementById(this.menuItem_objects[b].divElement).className.replace("_regular","_regular")}},__setSizeOfAllSubMenus:function(){for(var a=0;a<this.menuItemObj.menuItemsOrder.length;a++){var b=this.menuItemObj.menuItemsOrder[a];b&&this.__setSizeOfSubMenus(b)}},__positionAllSubMenus:function(){for(var a=
0;a<this.menuItemObj.menuItemsOrder.length;a++){var b=this.menuItemObj.menuItemsOrder[a];b&&this.submenuGroups[b]&&this.__positionSubMenu(b)}},__positionSubMenu:function(a){try{var b=document.getElementById(this.submenuGroups[a]),c=this.menuItemObj.submenuType[this.menuItems[a].depth],d=document.getElementById(this.menuItem_objects[a].divElement);if(c=="top")b.style.left=DHTMLSuite.commonObj.getLeftPos(d)+"px",b.style.top=DHTMLSuite.commonObj.getTopPos(d)+d.offsetHeight+"px";else{var c=2,h=0;DHTMLSuite.clientInfoObj.isMSIE&&
(c=0,h=3);b.style.left=DHTMLSuite.commonObj.getLeftPos(d)+d.offsetWidth+b.offsetWidth>Math.max(document.body.scrollLeft,document.documentElement.scrollLeft)+document.body.clientWidth?DHTMLSuite.commonObj.getLeftPos(d)-b.offsetWidth-c+"px":DHTMLSuite.commonObj.getLeftPos(d)+d.offsetWidth+c+"px";var f=DHTMLSuite.commonObj.getTopPos(d)+b.offsetHeight-(Math.max(document.body.scrollTop,document.documentElement.scrollTop)+document.body.clientHeight);if(f>0){var e=Math.floor(b.offsetHeight/b.children.length),
g=Math.min(Math.ceil(f/e)*e,b.offsetHeight-d.offsetHeight);b.style.top=DHTMLSuite.commonObj.getTopPos(d)-g-h+"px"}else b.style.top=DHTMLSuite.commonObj.getTopPos(d)-h+"px"}if(DHTMLSuite.clientInfoObj.isMSIE){var i=document.getElementById(this.submenuIframes[a]);i.style.left=b.style.left;i.style.top=b.style.top;i.style.width=b.clientWidth+"px";i.style.height=b.clientHeight+"px"}}catch(j){}},__setSizeOfSubMenus:function(a){try{var b=document.getElementById(this.submenuGroups[a]),c=Math.max(b.offsetWidth,
document.getElementById(this.menuItem_objects[a].divElement).offsetWidth);if(this.menuItems[a].submenuWidth)c=this.menuItems[a].submenuWidth;c>400&&(c=120);c+="";c.indexOf("%")==-1&&(c+="px");b.style.width=c;if(DHTMLSuite.clientInfoObj.isMSIE){var d=document.getElementById(this.submenuIframes[a]);d.style.width=b.style.width;d.style.height=b.style.height}}catch(h){}},__repositionMenu:function(a){a.menuBarObj.style.top=document.documentElement.scrollTop+"px"},__menuItemRollOver:function(a){var b=a.id.replace(/[^0-9]/g,
"");a.className="DHTMLSuite_menuBar_menuItem_over_"+this.menuItems[b].depth},__menuItemRollOut:function(a){var b=a.id.replace(/[^0-9]/g,"");a.className="DHTMLSuite_menuBar_menuItem_"+this.menuItems[b].depth},__menuNavigate:function(a){a.id.replace(/[^0-9]/g,"")},__setBasicEvents:function(){DHTMLSuite.commonObj.addEvent(document.documentElement,"click",this.hideSubMenus);DHTMLSuite.commonObj.addEvent(document.documentElement,"mouseup",this.hideSubMenus)}};
