/*

 DHTML Suite for Applications.
 Copyright (C)2006  Alf Magne Kalleland(post@dhtmlgoodies.com)

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option)any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

 www.dhtmlgoodies.com
 Alf Magne Kalleland
*/
if(!window.DHTMLSuite)var DHTMLSuite={};if(!String.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/,"")};var DHTMLSuite_funcs={};if(!window.DHTML_SUITE_THEME)var DHTML_SUITE_THEME="blue";if(!window.DHTML_SUITE_THEME_FOLDER)var DHTML_SUITE_THEME_FOLDER="../themes/";if(!window.DHTML_SUITE_JS_FOLDER)var DHTML_SUITE_JS_FOLDER="../js/separateFiles/";var DHTMLSuite={},standardObjectsCreated=!1;DHTMLSuite.eventEls=[];
var widgetDep={formValidator:["dhtmlSuite-formUtil.js"],paneSplitter:["dhtmlSuite-paneSplitter.js","dhtmlSuite-paneSplitterModel.js","dhtmlSuite-dynamicContent.js","ajax.js"],menuBar:["dhtmlSuite-menuBar.js","dhtmlSuite-menuItem.js","dhtmlSuite-menuModel.js"],windowWidget:["dhtmlSuite-windowWidget.js","dhtmlSuite-resize.js","dhtmlSuite-dragDropSimple.js","ajax.js","dhtmlSuite-dynamicContent.js"],colorSlider:["dhtmlSuite-colorWidgets.js","dhtmlSuite-colorUtil.js","dhtmlSuite-slider.js"],colorPalette:["dhtmlSuite-colorWidgets.js",
"dhtmlSuite-colorUtil.js"],calendar:["dhtmlSuite-calendar.js","dhtmlSuite-dragDropSimple.js"],dragDropTree:["dhtmlSuite-dragDropTree.js"],slider:["dhtmlSuite-slider.js"],dragDrop:["dhtmlSuite-dragDrop.js"],imageEnlarger:["dhtmlSuite-imageEnlarger.js","dhtmlSuite-dragDropSimple.js"],imageSelection:["dhtmlSuite-imageSelection.js"],floatingGallery:["dhtmlSuite-floatingGallery.js","dhtmlSuite-mediaModel.js"],contextMenu:["dhtmlSuite-contextMenu.js","dhtmlSuite-menuBar.js","dhtmlSuite-menuItem.js","dhtmlSuite-menuModel.js"],
dynamicContent:["dhtmlSuite-dynamicContent.js","ajax.js"],textEdit:["dhtmlSuite-textEdit.js","dhtmlSuite-textEditModel.js","dhtmlSuite-listModel.js"],listModel:["dhtmlSuite-listModel.js"],resize:["dhtmlSuite-resize.js"],dragDropSimple:["dhtmlSuite-dragDropSimple.js"],dynamicTooltip:["dhtmlSuite-dynamicTooltip.js","dhtmlSuite-dynamicContent.js","ajax.js"],modalMessage:["dhtmlSuite-modalMessage.js","dhtmlSuite-dynamicContent.js","ajax.js"],tableWidget:["dhtmlSuite-tableWidget.js","ajax.js"],progressBar:["dhtmlSuite-progressBar.js"],
tabView:["dhtmlSuite-tabView.js","dhtmlSuite-dynamicContent.js","ajax.js"],infoPanel:["dhtmlSuite-infoPanel.js","dhtmlSuite-dynamicContent.js","ajax.js"],form:["dhtmlSuite-formUtil.js","dhtmlSuite-dynamicContent.js","ajax.js"],autoComplete:["dhtmlSuite-autoComplete.js","ajax.js"],chainedSelect:["dhtmlSuite-chainedSelect.js","ajax.js"]},depCache={};
DHTMLSuite.include=function(a){if(widgetDep[a])for(var a=widgetDep[a],b=0;b<a.length;b++)depCache[a[b]]||(document.write("<script"),document.write(' language="javascript"'),document.write(' type="text/javascript"'),document.write(' src="'+DHTML_SUITE_JS_FOLDER+a[b]+'">'),document.write("<\/script>"),depCache[a[b]]=!0);else alert("Cannot find the files for widget "+a+". Please verify that the name is correct")};
DHTMLSuite.discardElement=function(a){var a=DHTMLSuite.commonObj.getEl(a),b=document.getElementById("IELeakGBin");if(!b)b=document.createElement("DIV"),b.id="IELeakGBin",b.style.display="none",document.body.appendChild(b);b.appendChild(a);b.innerHTML=""};
DHTMLSuite.createStandardObjects=function(){DHTMLSuite.clientInfoObj=new DHTMLSuite.clientInfo;DHTMLSuite.clientInfoObj.init();if(!DHTMLSuite.configObj)DHTMLSuite.configObj=new DHTMLSuite.config,DHTMLSuite.configObj.init();DHTMLSuite.commonObj=new DHTMLSuite.common;DHTMLSuite.variableStorage=new DHTMLSuite.globalVariableStorage;DHTMLSuite.commonObj.init();DHTMLSuite.domQueryObj=new DHTMLSuite.domQuery;DHTMLSuite.commonObj.addEvent(window,"unload",function(){DHTMLSuite.commonObj.__clearMemoryGarbage()});
standardObjectsCreated=!0};DHTMLSuite.config=function(){};DHTMLSuite.config.prototype={init:function(){this.imagePath=DHTML_SUITE_THEME_FOLDER+DHTML_SUITE_THEME+"/images/";this.defaultCssPath=this.cssPath=DHTML_SUITE_THEME_FOLDER+DHTML_SUITE_THEME+"/css/";this.defaultImagePath=this.imagePath},setCssPath:function(a){this.cssPath=a},resetCssPath:function(){this.cssPath=this.defaultCssPath},resetImagePath:function(){this.imagePath=this.defaultImagePath},setImagePath:function(a){this.imagePath=a}};
DHTMLSuite.globalVariableStorage=function(){this.menuBar_highlightedItems=[];this.arrayOfDhtmlSuiteObjects=this.arrayDSObjects=[];this.ajaxObjects=[]};DHTMLSuite.globalVariableStorage.prototype={};DHTMLSuite.common=function(){this.cssCacheStatus=this.okToSelect=!0;this.eventEls=[]};
DHTMLSuite.common.prototype={init:function(){this.loadedCSSFiles=[]},loadCSS:function(a,b){!b&&b!==!1&&(b=!0);if(!this.loadedCSSFiles[a]){this.loadedCSSFiles[a]=!0;var c=document.createElement("LINK");this.cssCacheStatus||(a+=a.indexOf("?")>=0?"&":"?",a=a+"rand="+Math.random());c.href=b?DHTMLSuite.configObj.cssPath+a:a;c.rel="stylesheet";c.media="screen";c.type="text/css";document.getElementsByTagName("HEAD")[0].appendChild(c)}},__setTextSelOk:function(a){this.okToSelect=a},__isTextSelOk:function(){return this.okToSelect},
setCssCacheStatus:function(a){this.cssCacheStatus=a},getEl:function(a){if(typeof a=="string"){if(document.getElementById(a))return document.getElementById(a);if(document.forms[a])return document.forms[a];if(document[a])return document[a];if(window[a])return window[a]}return a},isArray:function(a){if(a.constructor.toString().indexOf("Array")!=-1)return!0;return!1},getStyle:function(a,b){a=this.getEl(a);if(document.defaultView&&document.defaultView.getComputedStyle){var c=null,d=document.defaultView.getComputedStyle(a,
"");d&&(c=d[b]);return a.style[b]||c}if(document.documentElement.currentStyle&&DHTMLSuite.clientInfoObj.isMSIE)return a.currentStyle&&(value=a.currentStyle[b]),a.style[b]||null;return a.style[b]},getLeftPos:function(a){if(document.getBoxObjectFor&&a.tagName!="INPUT"&&a.tagName!="SELECT"&&a.tagName!="TEXTAREA")return document.getBoxObjectFor(a).x;for(var b=a.offsetLeft;(a=a.offsetParent)!=null;)a.tagName!="HTML"&&(b+=a.offsetLeft,document.all&&(b+=a.clientLeft));return b},getTopPos:function(a){if(document.getBoxObjectFor&&
a.tagName!="INPUT"&&a.tagName!="SELECT"&&a.tagName!="TEXTAREA")return document.getBoxObjectFor(a).y;for(var b=a.offsetTop;(a=a.offsetParent)!=null;)a.tagName!="HTML"&&(b+=a.offsetTop-a.scrollTop,document.all&&(b+=a.clientTop));b+=Math.max(document.body.scrollTop,document.documentElement.scrollTop);return b},getCookie:function(a){var b=document.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!=document.cookie.substring(0,a.length))return null;if(b==-1)return null;a=document.cookie.indexOf(";",c);if(a==
-1)a=document.cookie.length;return unescape(document.cookie.substring(c,a))},setCookie:function(a,b,c,d,e,f){c*=864E5;var g=new Date((new Date).getTime()+c),a=a+"="+escape(b)+(c?";expires="+g.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"");document.cookie=a},deleteCookie:function(a,b,c){if(this.getCookie(a))document.cookie=a+"="+(b?";path="+b:"")+(c?";domain="+c:"")+";expires=Thu, 01-Jan-1970 00:00:01 GMT"},cancelEvent:function(){return!1},addEvent:function(a,b,c,d){d||(d=
"");a.attachEvent?(typeof DHTMLSuite_funcs[b+c+d]!="function"&&(DHTMLSuite_funcs[b+c+d]=function(){c.apply(window.event.srcElement)},a.attachEvent("on"+b,DHTMLSuite_funcs[b+c+d])),a=null):a.addEventListener(b,c,!1);this.__addEventEl(a)},removeEvent:function(a,b,c,d){a.detachEvent?(a.detachEvent("on"+b,DHTMLSuite_funcs[b+c+d]),DHTMLSuite_funcs[b+c+d]=null):a.removeEventListener(b,c,!1)},__clearMemoryGarbage:function(){if(DHTMLSuite.clientInfoObj.isMSIE){for(var a=0;a<DHTMLSuite.eventEls.length;a++)try{var b=
DHTMLSuite.eventEls[a];b.onclick=null;b.onmousedown=null;b.onmousemove=null;b.onmouseout=null;b.onmouseover=null;b.onmouseup=null;b.onfocus=null;b.onblur=null;b.onkeydown=null;b.onkeypress=null;b.onkeyup=null;b.onselectstart=null;b.ondragstart=null;b.oncontextmenu=null;b=b.onscroll=null}catch(c){}for(a in DHTMLSuite.variableStorage.arrayDSObjects)DHTMLSuite.variableStorage.arrayDSObjects[a]=null;window.onbeforeunload=null;DHTMLSuite=window.onunload=null}},__addEventEl:function(a){DHTMLSuite.eventEls[DHTMLSuite.eventEls.length]=
a},getSrcElement:function(a){var b;if(a.target)b=a.target;else if(a.srcElement)b=a.srcElement;if(b.nodeType==3)b=b.parentNode;return b},getKeyFromEvent:function(a){a=this.getKeyCode(a);return String.fromCharCode(a)},getKeyCode:function(a){if(a.keyCode)code=a.keyCode;else if(a.which)code=a.which;return code},isObjectClicked:function(a,b){var c=this.getSrcElement(b);if(c==a)return!0;for(;c.parentNode&&c.tagName.toLowerCase()!="html";)if(c=c.parentNode,c==a)return!0;return!1},getObjectByClassName:function(a,
b){var c=this.getSrcElement(a);if(c.className==b)return c;for(;c&&c.tagName.toLowerCase()!="html";)if(c=c.parentNode,c.className==b)return c;return!1},getObjectByAttribute:function(a,b){var c=this.getSrcElement(a),d=c.getAttribute(b);d||(d=c[b]);if(d)return c;for(;c&&c.tagName.toLowerCase()!="html";)if(c=c.parentNode,(d=c.getAttribute("attribute"))||(d=c[b]),d)return c;return!1},getUniqueId:function(){var a=Math.random()+"",a=a.replace(".",""),b=Math.random()+"",b=b.replace(".","");return a+b},getAssociativeArrayFromString:function(a){if(a){for(var b=
[],a=a.split(/,/g),c=0;c<a.length;c++){var d=a[c].split(/:/);b[d[0]]=d[1]}return b}},correctPng:function(a){a=DHTMLSuite.commonObj.getEl(a);a.outerHTML="<span style=\"display:inline-block;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.src+"',sizingMethod='scale');width:"+a.width+";height:"+a.height+'"></span>'},__evaluateJs:function(a){for(var a=this.getEl(a),a=a.getElementsByTagName("SCRIPT"),b="",c=0;c<a.length;c++)if(a[c].src){document.getElementsByTagName("head");var d=document.createElement("script");
d.setAttribute("type","text/javascript");d.setAttribute("src",a[c].src)}else DHTMLSuite.clientInfoObj.isOpera?b=b+a[c].text+"\n":b+=a[c].innerHTML;b&&this.__installScript(b)},__installScript:function(a){try{a&&(window.execScript?window.execScript(a):window.setTimeout(a,0))}catch(b){}},__evaluateCss:function(a){for(var a=this.getEl(a),a=a.getElementsByTagName("STYLE"),b=document.getElementsByTagName("HEAD")[0],c=0;c<a.length;c++)b.appendChild(a[c])}};DHTMLSuite.clientInfo=function(){};
DHTMLSuite.clientInfo.prototype={init:function(){this.browser=navigator.userAgent;this.isOpera=this.browser.toLowerCase().indexOf("opera")>=0?!0:!1;this.isFirefox=this.browser.toLowerCase().indexOf("firefox")>=0?!0:!1;this.isMSIE=this.browser.toLowerCase().indexOf("msie")>=0?!0:!1;this.isOldMSIE=this.browser.toLowerCase().match(/msie\s[0-6]/gi)?!0:!1;this.isSafari=this.browser.toLowerCase().indexOf("safari")>=0?!0:!1;this.navigatorVersion=navigator.appVersion.replace(/.*?MSIE\s(\d\.\d).*/g,"$1")/
1;this.isOldMSIE=this.isMSIE&&this.navigatorVersion<7?!0:!1},getBrowserWidth:function(){if(self.innerWidth)return self.innerWidth;return document.documentElement.offsetWidth},getBrowserHeight:function(){if(self.innerHeight)return self.innerHeight;return document.documentElement.offsetHeight}};DHTMLSuite.domQuery=function(){document.getElementsByClassName=this.getElementsByClassName;document.getElementsByAttribute=this.getElementsByAttribute};DHTMLSuite.domQuery.prototype={};
